FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod ./
COPY main.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o go-backend .

FROM alpine:3.21
RUN apk --no-cache add ca-certificates curl
WORKDIR /root/
COPY --from=builder /app/go-backend .
EXPOSE 8080
CMD ["./go-backend"]
